### ISSUE TITLE
Fix 3. Scanning a serverless function

### ISSUE THREAD

**Issue by ryanchauvin** [twistlock/docs#163]
https://docs.twistlock.com/docs/compute_edition/vulnerability_management/serverless_functions.html#scanning-a-serverless-function

4. C. Says the following:
Wildcards are supported. See the table at the top of the page for the supported syntax and examples.

However, there is no table at the top of the page.

**Comment by iansk** [comment]
Thanks @ryanchauvin. I just removed that sentence. I don't think we ever had a table at the top.
