### ISSUE TITLE
Include OpenShift support in this System Requirements

### ISSUE THREAD

**Issue by harisrini** [twistlock/docs#164]
https://docs.paloaltonetworks.com/prisma/prisma-cloud/20-09/prisma-cloud-compute-edition-admin/install/system_requirements.html

Doesn't include OpenShift support details.

**Comment by iansk** [comment]
@harisrini It does contain OpenShift support details. See screenshot

<img width="1079" alt="openshift_sys_reqs" src="https://user-images.githubusercontent.com/6518946/94173540-b0348d80-fe59-11ea-95cd-30003a477cd0.png">

Closing. If you need something else beyond this, reopen with details.
