### ISSUE TITLE
fields query parameter should be removed

### ISSUE THREAD

**Issue by iansk** [twistlock/docs#232]
from customer case, the 'field' from the query string is internal and should be removed from API docs:

https://cdn.twistlock.com/docs/api/twistlock_api.html#containers_download_get

"For example we'd like to get the labels of the container into the report but fields=labels or fields=info.labels (deducted from the JSON report) doesn't work.
Example call: https://twistlock.security.kmo.zone:8083/api/v1/containers/download?id=1d6f6c8c304ab9cffb13d30ecc6b1317f6ea7761496ffa4b780632c3ed16b990&fields=labels
Where do we find the supported values or the fields parameter?"

(Reported by @joshfalgout on Oct 1, 2020)

**Comment by hf-cjharries** [comment]
Does the extend to other API calls that have a `fields` query parameter? For example, [`/hosts/info` also has `fields`](https://cdn.twistlock.com/docs/api/twistlock_api.html#hosts_info_get). Is this issue saying that the field is not exposed to the API anywhere or only this specific call?

**Comment by joshfalgout** [comment]
Yes, this extends to the other api calls that expect a fields input

**Comment by ssugandh** [comment]
Done as part of https://spring.paloaltonetworks.com/twistlock/twistlock/issues/38593 and https://redlock.atlassian.net/browse/PCSUP-9836.

**Comment by iansk** [comment]
Resolved. See https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/365
