### ISSUE TITLE
Trust Groups API update

### ISSUE THREAD

**Issue by joshfalgout** [twistlock/docs#240]
Customer Feedback and bug report

Documentation: PUT /trust/data
• This is missing examples of queries. All other endpoints have examples of curl commands.
• For the body, it only has documentation for the groups, where it needs documentation for policy as well.
o An actual payload looks like {
“policy”: {…},
“groups”: {…}
}

• The images field: this should be a list of strings, not a string.
o Is this the same for the layers field?

• I would like some clarification over the _id and the name fields. For the rest of the API, it seems like the _id field is only really used when returning data via get requests, and the name field is used to define the name of the object. Whereas here, it seems like the name field is ignored completely when creating groups, and it uses the _id field. I don’t think this is the right behaviour.

**Comment by iansk** [comment]
This is no longer a supported endpoint.

See "Upcoming deprecations" here:

https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-04/prisma-cloud-compute-edition-release-notes/release-information/release-notes-21-04-update1.html

See supported endpoints are here:

https://prisma.pan.dev/docs/cloud/cwpp/stable-endpoints

Closing.
