### ISSUE TITLE
Required / Optional fields for API documentation

### ISSUE THREAD

**Issue by joshfalgout** [twistlock/docs#241]
Customer feedback:

Documentation: in general
• I think it would be nice to see what fields are mandatory and which ones are optional.

**Comment by iansk** [comment]
I've aware of this shortcoming, and it's in the list of improvements that's being considered for a subsequent release. If the improvement is scheduled for a release, it'll be something that will be formally added to our product roadmap and that we'll be able to communicate to customers.
