### ISSUE TITLE
Need to add '-X POST' to the install script on "Automate Defender install" documentation

### ISSUE THREAD

**Issue by mxrehan** [twistlock/docs#254]
Customer confirmed without adding  "-X POST" to the install script, they are unable to install the defender.
Our documentation does not mention this. 

Please update the doc accordingly.

Step 4 should be 

curl -X POST \
-H "authorization: Bearer <TOKEN> \
https://<COMPUTE_CONSOLE>:8083/api/v1/scripts/defender.sh \
-o defender.sh && \
chmod a+x defender.sh && \
sudo ./defender.sh -c "<CONSOLE>" -d "none"

**Comment by iansk** [comment]
@mxrehan Thanks for the report. Can you please send me a link to page in the docs?

**Comment by mxrehan** [comment]
https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/api/automate_defender_install.html

**Comment by mxrehan** [comment]
I have created PR for this issue now.

https://github.com/twistlock/docs/pull/268

**Comment by iansk** [comment]
This has been fixed. @mxrehan submitted a PR, and it's been merged.
