### ISSUE TITLE
Search issue on main page

### ISSUE THREAD

**Issue by NikP-PAN** [twistlock/docs#305]
1. Navigate to https://docs.twistlock.com/docs/
2. enter a search term and press enter on the keyboard. Notice that the text clears and no search results are returned.
3. Enter another search term and click on the magnify glass. Notice that search results are returned

I am thinking that when you press enter on the keyboard, it defaults to the 'x' to clear the search box instead of initiate a search

**Comment by iansk** [comment]
@NikP-PAN Thanks for the report. Search is now fixed. Pressing enter properly submits the keywords and opens the dialog with the results.

cc: @joshfalgout

**Comment by iansk** [comment]
See https://github.com/twistlock/docs/pull/310
