### ISSUE TITLE
update API documentation for backup endpoints

### ISSUE THREAD

**Issue by joshfalgout** [twistlock/docs#355]
Here is the data, this needs to be added to the API docs

***
/api/v1/backups  GET

curl -k \
-u <USER> \
https://<CONSOLE>:<PORT>/api/v1/backups
***

***
/api/v1/backups POST

curl -k \
-u <USER> \
-X POST \
-d \
'
"backupName"
' \
https://<CONSOLE>:<PORT>/api/v1/backups
***

***
/api/v1/backups/{id}  GET

curl -k \
-u <USER> \
https://<CONSOLE>:<PORT>/api/v1/backups/backupName-20.12.531-1613058945.tar.gz

Sample data from the api/v1/backups GET call
{
    "name": "backupName",
    "release": "20.12.531",
    "time": "2021-02-11T15:55:45Z",
    "id": "backupName-20.12.531-1613058945.tar.gz"
}
***

***
/api/v1/backups/{id}  DELETE**

curl -k \
-u <USER> \
-X DELETE \
https://<CONSOLE>:<PORT>/api/v1/backups/backupName-20.12.531-1613058945.tar.gz

Sample data from the api/v1/backups GET call
{
    "name": "backupName",
    "release": "20.12.531",
    "time": "2021-02-11T15:55:45Z",
    "id": "backupName-20.12.531-1613058945.tar.gz"
}

**/api/v1/backups/{id}  PATCH

curl -k \
-u <USER> \
-X PATCH \
-d \
'
"backupNameEdited"
' \
https://<CONSOLE>:<PORT>/api/v1/backups/backupName-20.12.531-1613058945.tar.gz

Sample data from the api/v1/backups GET call
{
    "name": "backupName",
    "release": "20.12.531",
    "time": "2021-02-11T15:55:45Z",
    "id": "backupName-20.12.531-1613058945.tar.gz"
}
***

***
/api/v1/backups/{id}  POST

curl -k \
-u <USER> \
-X POST \
-d @backupName-20.12.531-1613058945.tar.gz \
https://<CONSOLE>:<PORT>/api/v1/backups/backupName-20.12.531-1613058945.tar.gz
***

***
/api/v1/backups/{id}/restore  POST

curl -k \
-u <USER> \
-X POST \
https://<CONSOLE>:<PORT>/api/v1/backups/backupName-20.12.531-1613058945.tar.gz
***

**Comment by iansk** [comment]
Since 21.08, backups isn't a versioned endpoint. We don't offer docs for non-versioned endpoints. Closing.
