### ISSUE TITLE
Update API Docs - /settings/scan

### ISSUE THREAD

**Issue by NikP-PAN** [twistlock/docs#376]
https://cdn.twistlock.com/docs/api/twistlock_api.html#settings_scan_post

The example in the doc requires **registryScanRetentionDays** to function correctly. Like so:

`curl -k \
-u <USER> \
-H 'Content-Type: application/json' \
-X POST \
-d \
'{
 "imagesScanPeriodMs":86400000,
 "containersScanPeriodMs": 86400000,
 "systemScanPeriodMs": 86400000,
 "serverlessScanPeriodMs": 604800000,
 "registryScanRetentionDays": 1,
 "registryScanPeriodMs":604800000
}' \
https://<CONSOLE>:8083/api/v1/settings/scan `

**Comment by iansk** [comment]
Starting with 21.08, this isn't a versioned endpoint. No docs for non-versioned endpoints. Closing.
