### ISSUE TITLE
API documentation - settings/registry documentation

### ISSUE THREAD

**Issue by joshfalgout** [twistlock/docs#384]
Customer request:

This is more of a documentation request. Documentation for this API https://cdn.twistlock.com/docs/api/twistlock_api.html#settings_registry_post does not specify which attributes are required based on the 'version' type that is being passed. It should reflect which fields are required based on the type being configured.

**Comment by iansk** [comment]
@joshfalgout Good feedback. Discussed this with @KICKdesigns today. We'll try to get this addressed.

**Comment by KICKdesigns** [comment]
@iansk The POST endpoint wasn't in the Consule UI, so we skipped that previously. Do you want to go back and do that one anyways with just the command line?

**Comment by iansk** [comment]
Resolved. See https://prisma.pan.dev/api/cloud/cwpp/settings#operation/post-settings-registry
