### ISSUE TITLE
Ports that the defender uses to connect to PCEE

### ISSUE THREAD

**Issue by jdong10** [twistlock/docs#46]
https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/install/install_openshift.html

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-reference-architecture-compute/platform_components/connectivity_flows.html

Both articles show that defender communicates to console on port 8084. This is only true for PCCE. Should be changes to 443 or indicated somewhere in the article.

**Comment by solalraveh** [comment]
PR #91 should take care of most of it when merged. the flowchart PNG needs to be updated too.
