### ISSUE TITLE
address docs/ui drift for installing Defender

### ISSUE THREAD

**Issue by tkishel** [twistlock/docs#545]
The Console UI no longer matches what is referenced in this documentation ...

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/install/install_kubernetes.html

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/install/install_openshift_4.html

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/install/install_openshift_3_11.html

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/upgrade/upgrade_defender_daemonset.html

In addition ...

Variables containing URLs and hostnames are inaccurately named with "ADDR".

Variables are unnecessary named with "API" when the user is executing the twistcli command rather than accessing an endpoint. 

Some twistcli commands are missing  `\` characters.

Formatting and language arbitrarily vary across the install and upgrade pages for kubernetes and openshift.

**Comment by iansk** [comment]
Closing. PR submitted and merged.
