### ISSUE TITLE
k3s support

### ISSUE THREAD

**Issue by sgordon46** [twistlock/docs#594]
It sounds like k3s is supported as of Hamilton.

https://panw-global.slack.com/archives/CDN10Q0NT/p1625254788369300?thread_ts=1624367498.158100&cid=CDN10Q0NT

Can this be added to the docs?
@iansk @morellonet

**Comment by iansk** [comment]
@sgordon46 We'll discuss at our PM team meeting, and then I'll respond back here.

**Comment by iansk** [comment]
K3S isn't currently supported. We recently added support for Rancher RKE2, which is based on K3S, but they're not the same. We test and, therefore, support RKE2. When we add support for K3S, we'll update our [system requirements](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/install/system_requirements.html).
