### ISSUE TITLE
Add Host Defender installation to Admin. guide

### ISSUE THREAD

**Issue by harisrini** [twistlock/docs#60]
Admin. guide is missing Host Defender Install instructions.
Include that for both Linux and Windows.
Link that up to Defender Types and index it the section

https://docs.paloaltonetworks.com/prisma/prisma-cloud/20-04/prisma-cloud-compute-edition-admin/install/install_defender.html

Consider for - upcoming update cycles before Fermat, if possible. Else for Fermat.

**Comment by iansk** [comment]
Covered by the Fermat doc plan. Closing.
